// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKYB0qJf-R80yvngqKJGhW1ST53sA6Mrw',
    appId: '1:123721986259:web:111f0c1fd3d6129ec0a426',
    messagingSenderId: '123721986259',
    projectId: 'gestionakom',
    authDomain: 'gestionakom.firebaseapp.com',
    storageBucket: 'gestionakom.appspot.com',
    measurementId: 'G-9LR2XYD6XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPqlt1isio6hMWNfeUOBwLR99asZ4EnLs',
    appId: '1:123721986259:android:61133717862df37ac0a426',
    messagingSenderId: '123721986259',
    projectId: 'gestionakom',
    storageBucket: 'gestionakom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt5TPpZQVrINHiRdyR72H1uR2WrS8akSc',
    appId: '1:123721986259:ios:6fc5008569b921fcc0a426',
    messagingSenderId: '123721986259',
    projectId: 'gestionakom',
    storageBucket: 'gestionakom.appspot.com',
    iosBundleId: 'com.example.gestionAkoum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt5TPpZQVrINHiRdyR72H1uR2WrS8akSc',
    appId: '1:123721986259:ios:6fc5008569b921fcc0a426',
    messagingSenderId: '123721986259',
    projectId: 'gestionakom',
    storageBucket: 'gestionakom.appspot.com',
    iosBundleId: 'com.example.gestionAkoum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKYB0qJf-R80yvngqKJGhW1ST53sA6Mrw',
    appId: '1:123721986259:web:b2ba6844077284b9c0a426',
    messagingSenderId: '123721986259',
    projectId: 'gestionakom',
    authDomain: 'gestionakom.firebaseapp.com',
    storageBucket: 'gestionakom.appspot.com',
    measurementId: 'G-MNFM151494',
  );
}
